- platform: mqtt
  name: "Garage Entry Lights Toggle Z-Wave"
  state_topic: "smartthings/Garage Entry Toggle Z-Wave/switch"
  command_topic: "smartthings/Garage Entry Toggle Z-Wave/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Garage Lights Toggle Z-Wave"
  state_topic: "smartthings/Garage Lights Toggle Z-Wave/switch"
  command_topic: "smartthings/Garage Lights Toggle Z-Wave/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Driveway Lights Toggle Z-Wave"
  state_topic: "smartthings/Driveway Toggle Z-Wave/switch"
  command_topic: "smartthings/Driveway Toggle Z-Wave/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Front Porch Lights Toggle Z-Wave"
  state_topic: "smartthings/Front Porch Toggle Z-Wave/switch"
  command_topic: "smartthings/Front Porch Toggle Z-Wave/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true

- platform: mqtt
  name: "Vestibule Lights Toggle Z-Wave"
  state_topic: "smartthings/Vestibule Toggle Z-Wave/switch"
  command_topic: "smartthings/Vestibule Toggle Z-Wave/switch"
  payload_on: "on"
  payload_off: "off"
  retain: true
