homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 186.97
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Detroit

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
sensor:
  platform: yr

# Text to speech
tts:
  platform: google

switch:
  platform: mqtt
  name: "Family Room Dimmer Z-Wave"
  state_topic: "smartthings/Family Room Dimmer Z-Wave/switch"
  command_topic: "smartthings/Family Room Dimmer Z-Wave/switch"
  brightness_state_topic: "smartthings/Family Room Dimmer Z-Wave/level"
  brightness_command_topic: "smartthings/Family Room Dimmer Z-Wave/level"
  payload_on: "on"
  payload_off: "off"
  retain: true

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_ID
  client_secret: !secret nest_client_secret
