homeassistant:
  name: HASS-1
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/Detroit
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_api_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# Store the history in an sqlite database
recorder:
  purge_days: 7

# View all events in a logbook
logbook:
  exclude:
      entities:
        - sensor.garage_door_time_in_state
        - sensor.garage_door_wifi_signal_strength
logger:
  default: info

# Track the sun
sun:

# Text to speech
tts:
  platform: google

cover:
  - platform: garadget
    covers:
      4a0042000351353530353431:
        username: !secret garadget_username
        password: !secret garadget_password
        name: Garage door

ring:
  username: !secret ring_username
  password: !secret ring_password

nest:
  client_id: !secret nest_client_ID
  client_secret: !secret nest_client_secret

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password

light:
  - platform: mqtt_json
    name: "SN1 LED"
    state_topic: "bruh/sensornode1"
    command_topic: "bruh/sensornode1/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
    
group: !include groups.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
lock: !include_dir_merge_list locks/
binary_sensor: !include_dir_merge_list binary_sensors/
automation: !include_dir_merge_list automations/
