- platform: mqtt
  name: Front Door Lock
  state_topic: "smartthings/Front Door Lock Z-Wave/lock"
  command_topic: "smartthings/Front Door Lock Z-Wave/lock"
  payload_lock: "locked"
  payload_unlock: "unlocked"
  optimistic: false
  retain: true

- platform: mqtt
  name: Garage Entry Lock
  state_topic: "smartthings/Garage Entry Lock Z-Wave/lock"
  command_topic: "smartthings/Garage Entry Lock Z-Wave/lock"
  payload_lock: "locked"
  payload_unlock: "unlocked"
  optimistic: false
  retain: true
