- alias: 'Turn Garage Lights On'
  trigger:
    - platform: state
      entity_id: binary_sensor.garage_entry_door_sensor_zwave
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.garage_lights_toggle_zwave

- alias: 'Turn Garage Lights Off'
  trigger:
    #If door has been opened and then closed for x amount of time
    - platform: state
      entity_id: binary_sensor.garage_entry_door_sensor_zwave
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 15
        seconds: 0
    #If it's been on too long
    - platform: state
      entity_id: switch.garage_lights_toggle_zwave
      to: 'on'
      # Alias for 'to'
      state: 'on'
      for:
        hours: 0
        minutes: 30
        seconds: 0
  action:
    - service: switch.turn_off
      entity_id: switch.garage_lights_toggle_zwave

- alias: 'Turn Garage Entry Light On'
  trigger:
    #If door opens
    - platform: state
      entity_id: binary_sensor.garage_entry_door_sensor_zwave
      from: 'off'
      to: 'on'
    #If motion detected
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      to: 'on'
  action:
    service: switch.turn_on
    entity_id: switch.garage_entry_toggle_zwave

- alias: 'Turn Garage Entry Light Off'
  trigger:
    #If no motion
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 0
        seconds: 15
    #If door has been opened and then closed for x amount of time
    - platform: state
      entity_id: binary_sensor.garage_entry_door_sensor_zwave
      from: 'on'
      to: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
    #If it's been on too long
    - platform: state
      entity_id: switch.garage_entry_toggle_zwave
      to: 'on'
      # Alias for 'to'
      state: 'on'
      for:
        hours: 0
        minutes: 10
        seconds: 0
  # only turn light off if there is no motion in the kitchen
  #condition:
    #condition: state
    #entity_id: binary_sensor.kitchen_motion_sensor
    #state: 'off'
  action:
    service: switch.turn_off
    entity_id: switch.garage_entry_toggle_zwave

- alias: 'Turn Kitchen Light On'
  #If motion is detected
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
    #Starting 1 hour before sunset
    - condition: sun
      after: sunset
      after_offset: "-1:00:00"
    #Cloudy day
    #- condition: numeric_state
      #entity_id: sensor.yr_cloudiness
      #above: 75
    #Low light levels
    - condition: numeric_state
      entity_id: sensor.kitchen_light_level
      below: 5
  action:
    service: switch.turn_on
    entity_id: switch.kitchen_dimmer_zwave

- alias: 'Turn Kitchen Light Off'
  #If no motion after x amount of time
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_dimmer_zwave

- alias: 'Turn Living Room Lights On At Sunset'
  #When solar elevation is low
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 3.5
  action:
    service: switch.turn_on
    entity_id: switch.family_room_dimmer_zwave
